# Generated by Django 4.2.3 on 2023-08-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_subscribedusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribedusers',
            options={'verbose_name_plural': 'Subscribed users'},
        ),
    ]
