# Generated by Django 4.2.3 on 2023-07-26 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, default='no-products-found.png', null=True, upload_to='photos/products'),
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(max_length=10, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('gender_image', models.ImageField(blank=True, null=True, upload_to='photos/genders/')),
                ('categories', models.ManyToManyField(blank=True, related_name='gender_categories', to='shop_app.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='genders',
            field=models.ManyToManyField(blank=True, related_name='category_genders', to='shop_app.gender'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_app.gender'),
        ),
    ]
