# Generated by Django 4.2.3 on 2023-08-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_rename_collection_discount_percentage_product_additional_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_price_db',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
