# Generated by Django 4.2.3 on 2023-08-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_alter_product_discounted_price_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_discount_percentage',
        ),
        migrations.AddField(
            model_name='collection',
            name='images',
            field=models.ImageField(blank=True, default='no-products-found.png', null=True, upload_to='photos/collections'),
        ),
    ]
