# Generated by Django 4.1.5 on 2023-07-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_shipping_cost_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_cost_percent',
            field=models.FloatField(),
        ),
    ]
