# Generated by Django 4.1.5 on 2023-08-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_payment_orderproduct_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_cost_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
