# Generated by Django 4.2.3 on 2023-08-09 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_variation'),
        ('orders', '0007_remove_order_shipping_cost_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product_quantity',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_app.product'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='variations',
            field=models.ManyToManyField(blank=True, to='shop_app.variation'),
        ),
    ]
