# Generated by Django 4.2.3 on 2023-09-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderproduct_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingconfig',
            name='shipping_cost_percent',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
